drop table if exists EMPLOYEE;
create table EMPLOYEE (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	salary INT,
	dept VARCHAR(50),
	city VARCHAR(50),
	country VARCHAR(50),
	gender VARCHAR(50)
);
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (1, 'Maren', 'Kesby', 'mkesby0@symantec.com', 3135, 'Training', 'Stockholm', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (2, 'Lanita', 'Spurrier', 'lspurrier1@mail.ru', 7105, 'Accounting', 'Jönköping', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (3, 'Jarrett', 'Rawlinson', 'jrawlinson2@harvard.edu', 1200, 'Support', 'Umeå', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (4, 'Walt', 'Menci', 'wmenci3@weather.com', 9942, 'Services', 'Stockholm', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (5, 'Adorne', 'Waind', 'awaind4@illinois.edu', 2717, 'Legal', 'Linköping', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (6, 'Shane', 'Bernhardsson', 'sbernhardsson5@epa.gov', 4960, 'Accounting', 'Boxholm', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (7, 'Timmie', 'McKern', 'tmckern6@dyndns.org', 5802, 'Accounting', 'Västervik', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (8, 'Olive', 'Gilks', 'ogilks7@free.fr', 4388, 'Sales', 'Filipstad', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (9, 'Brennan', 'Abramamovh', 'babramamovh8@woothemes.com', 5916, 'Support', 'Skinnskatteberg', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (10, 'Del', 'Mugglestone', 'dmugglestone9@phoca.cz', 3887, 'Marketing', 'Saltsjöbaden', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (11, 'Dionne', 'Keaves', 'dkeavesa@eepurl.com', 7148, 'Product Management', 'Trollhättan', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (12, 'Louella', 'O''Loghlen', 'lologhlenb@noaa.gov', 9061, 'Engineering', 'Mariestad', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (13, 'Kristofer', 'Pugh', 'kpughc@tmall.com', 8947, 'Engineering', 'Frösön', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (14, 'Dyan', 'D''Ambrogio', 'ddambrogiod@army.mil', 3128, 'Support', 'Emmaboda', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (15, 'Sarge', 'Wallwood', 'swallwoode@tripadvisor.com', 7794, 'Business Development', 'Gråbo', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (16, 'Winthrop', 'Aldous', 'waldousf@mail.ru', 5009, 'Marketing', 'Uppsala', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (17, 'Kati', 'Stenbridge', 'kstenbridgeg@spiegel.de', 6754, 'Services', 'Umeå', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (18, 'Cornela', 'Couldwell', 'ccouldwellh@freewebs.com', 8092, 'Product Management', 'Lindesberg', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (19, 'Adam', 'Willoughey', 'awillougheyi@whitehouse.gov', 8431, 'Human Resources', 'Valdemarsvik', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (20, 'Austine', 'Extence', 'aextencej@cdc.gov', 3912, 'Business Development', 'Boden', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (21, 'Pierette', 'Ghirigori', 'pghirigorik@ehow.com', 2422, 'Accounting', 'Västervik', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (22, 'Torrie', 'McVicar', 'tmcvicarl@ucoz.com', 9718, 'Legal', 'Brämhult', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (23, 'Jilli', 'Patsall', 'jpatsallm@examiner.com', 5582, 'Support', 'Tanumshede', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (24, 'Dania', 'Garnall', 'dgarnalln@ftc.gov', 5743, 'Services', 'Bjästa', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (25, 'Howie', 'Savidge', 'hsavidgeo@wikispaces.com', 5627, 'Human Resources', 'Västerås', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (26, 'Tish', 'Ralfe', 'tralfep@tripod.com', 7715, 'Training', 'Solna', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (27, 'Zuzana', 'Swinfen', 'zswinfenq@last.fm', 9400, 'Accounting', 'Nässjö', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (28, 'Karleen', 'Tobias', 'ktobiasr@cafepress.com', 2664, 'Engineering', 'Skövde', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (29, 'Edward', 'Crigin', 'ecrigins@tamu.edu', 9155, 'Legal', 'Stockholm', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (30, 'Dre', 'Blood', 'dbloodt@google.pl', 6199, 'Human Resources', 'Göteborg', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (31, 'Christoffer', 'Dolbey', 'cdolbeyu@vinaora.com', 9162, 'Legal', 'Stenungsund', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (32, 'Courtnay', 'De Domenicis', 'cdedomenicisv@w3.org', 6268, 'Accounting', 'Osby', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (33, 'Filmer', 'Fairlamb', 'ffairlambw@amazon.co.uk', 9237, 'Product Management', 'Örnsköldsvik', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (34, 'Amandie', 'Hardwin', 'ahardwinx@wikispaces.com', 9569, 'Support', 'Göteborg', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (35, 'Hetty', 'Fardell', 'hfardelly@mediafire.com', 7318, 'Accounting', 'Järna', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (36, 'Jenna', 'Braitling', 'jbraitlingz@chron.com', 3170, 'Marketing', 'Vällingby', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (37, 'Goldi', 'Murdy', 'gmurdy10@example.com', 2432, 'Services', 'Boden', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (38, 'Kristal', 'Vanyatin', 'kvanyatin11@home.pl', 7357, 'Support', 'Ytterby', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (39, 'Jessamine', 'Busse', 'jbusse12@slate.com', 7135, 'Business Development', 'Örnsköldsvik', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (40, 'Bud', 'Jenkyn', 'bjenkyn13@smh.com.au', 9456, 'Engineering', 'Vårby', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (41, 'Barbe', 'Ogborne', 'bogborne14@sun.com', 9735, 'Sales', 'Mariefred', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (42, 'Pryce', 'Habens', 'phabens15@livejournal.com', 7960, 'Legal', 'Jönköping', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (43, 'Karen', 'Girodier', 'kgirodier16@naver.com', 6430, 'Engineering', 'Munkedal', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (44, 'Christoper', 'Entissle', 'centissle17@gravatar.com', 4884, 'Services', 'Norrtälje', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (45, 'Jany', 'Semiras', 'jsemiras18@dropbox.com', 5641, 'Business Development', 'Skara', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (46, 'Imogen', 'Warrington', 'iwarrington19@joomla.org', 3305, 'Training', 'Uppsala', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (47, 'Gayle', 'Connah', 'gconnah1a@ihg.com', 7098, 'Training', 'Ystad', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (48, 'Stevena', 'Benditt', 'sbenditt1b@google.ca', 9657, 'Engineering', 'Enskede', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (49, 'Judon', 'Armes', 'jarmes1c@eventbrite.com', 2473, 'Support', 'Mariestad', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (50, 'Rosie', 'Grindlay', 'rgrindlay1d@apache.org', 7891, 'Legal', 'Stockholm', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (51, 'Hannah', 'Fearnyhough', 'hfearnyhough1e@prlog.org', 9300, 'Engineering', 'Billdal', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (52, 'Traver', 'Willox', 'twillox1f@loc.gov', 4546, 'Accounting', 'Umeå', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (53, 'Betteann', 'Gainsburgh', 'bgainsburgh1g@google.co.uk', 2665, 'Accounting', 'Mariestad', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (54, 'Lorrayne', 'Lepper', 'llepper1h@cnbc.com', 2035, 'Services', 'Arlöv', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (55, 'Cristen', 'Retter', 'cretter1i@state.tx.us', 1020, 'Training', 'Habo', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (56, 'Mitchel', 'Jelkes', 'mjelkes1j@google.pl', 9007, 'Marketing', 'Forshaga', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (57, 'Linn', 'Klimshuk', 'lklimshuk1k@example.com', 5091, 'Services', 'Laholm', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (58, 'Lydia', 'Goodband', 'lgoodband1l@reddit.com', 2839, 'Support', 'Vänersborg', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (59, 'Delila', 'Packwood', 'dpackwood1m@digg.com', 3795, 'Business Development', 'Nyköping', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (60, 'Sheilakathryn', 'Blofield', 'sblofield1n@zimbio.com', 1890, 'Training', 'Vallentuna', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (61, 'Eugenio', 'Kendall', 'ekendall1o@imdb.com', 8926, 'Accounting', 'Lycksele', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (62, 'Brittaney', 'Linzey', 'blinzey1p@de.vu', 7402, 'Support', 'Västerås', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (63, 'Damara', 'Dalgleish', 'ddalgleish1q@spiegel.de', 8093, 'Legal', 'Tanumshede', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (64, 'Lillian', 'Scarf', 'lscarf1r@rambler.ru', 6770, 'Accounting', 'Västerås', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (65, 'Gladi', 'Panons', 'gpanons1s@weibo.com', 2069, 'Human Resources', 'Spånga', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (66, 'Quinn', 'Epsley', 'qepsley1t@prnewswire.com', 8744, 'Sales', 'Tyringe', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (67, 'Letty', 'Klimov', 'lklimov1u@washingtonpost.com', 4865, 'Training', 'Umeå', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (68, 'Kitty', 'Crucetti', 'kcrucetti1v@nsw.gov.au', 3917, 'Product Management', 'Askersund', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (69, 'Noelani', 'Cossum', 'ncossum1w@rakuten.co.jp', 1409, 'Training', 'Norrköping', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (70, 'Hamlen', 'Healy', 'hhealy1x@hud.gov', 8180, 'Training', 'Uddevalla', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (71, 'Northrup', 'Fautly', 'nfautly1y@hatena.ne.jp', 6783, 'Engineering', 'Mjölby', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (72, 'Mitchell', 'Clark', 'mclark1z@mac.com', 1196, 'Research and Development', 'Bromma', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (73, 'Maura', 'Redsell', 'mredsell20@macromedia.com', 6661, 'Engineering', 'Tyringe', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (74, 'Harri', 'Jenking', 'hjenking21@skyrock.com', 2674, 'Product Management', 'Järfälla', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (75, 'Kelwin', 'Rhodef', 'krhodef22@usda.gov', 6255, 'Legal', 'Haninge', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (76, 'Aila', 'MacTrusty', 'amactrusty23@nih.gov', 5106, 'Support', 'Eksjö', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (77, 'Parrnell', 'Clow', 'pclow24@free.fr', 8281, 'Legal', 'Linköping', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (78, 'Cash', 'Thorneywork', 'cthorneywork25@hhs.gov', 2542, 'Legal', 'Åkersberga', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (79, 'Dieter', 'Blindt', 'dblindt26@ask.com', 3447, 'Research and Development', 'Arvidsjaur', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (80, 'Edy', 'Norcop', 'enorcop27@unc.edu', 3488, 'Business Development', 'Stockholm', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (81, 'Deb', 'Glowinski', 'dglowinski28@netvibes.com', 2146, 'Research and Development', 'Skellefteå', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (82, 'Julina', 'Shepland', 'jshepland29@rambler.ru', 9552, 'Support', 'Sundsvall', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (83, 'Ethelind', 'Gainfort', 'egainfort2a@mapquest.com', 3222, 'Engineering', 'Hammarö', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (84, 'Waylon', 'Perch', 'wperch2b@google.pl', 6022, 'Accounting', 'Borlänge', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (85, 'Dov', 'Brome', 'dbrome2c@globo.com', 5288, 'Legal', 'Asarum', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (86, 'Goraud', 'Kynder', 'gkynder2d@csmonitor.com', 5359, 'Human Resources', 'Kista', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (87, 'Griffie', 'Keyes', 'gkeyes2e@yahoo.com', 3433, 'Accounting', 'Skelleftehamn', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (88, 'Myrilla', 'Peschet', 'mpeschet2f@mapquest.com', 1315, 'Support', 'Bromma', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (89, 'Dorothee', 'Redferne', 'dredferne2g@adobe.com', 2420, 'Business Development', 'Fagersta', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (90, 'Ashil', 'Erwin', 'aerwin2h@sakura.ne.jp', 8935, 'Marketing', 'Danderyd', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (91, 'Jeanie', 'Clemson', 'jclemson2i@creativecommons.org', 4088, 'Services', 'Hallstahammar', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (92, 'Bellina', 'Stride', 'bstride2j@istockphoto.com', 7583, 'Sales', 'Örebro', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (93, 'Skippie', 'Farnan', 'sfarnan2k@jalbum.net', 8903, 'Accounting', 'Kungsbacka', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (94, 'Guglielmo', 'Kruschev', 'gkruschev2l@irs.gov', 4677, 'Training', 'Falun', 'SE', 'M');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (95, 'Tiphani', 'Damper', 'tdamper2m@issuu.com', 3234, 'Product Management', 'Emmaboda', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (96, 'Jaclyn', 'Williment', 'jwilliment2n@livejournal.com', 2039, 'Human Resources', 'Halmstad', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (97, 'Aleta', 'Enston', 'aenston2o@redcross.org', 2292, 'Product Management', 'Enskede', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (98, 'Zorine', 'Chislett', 'zchislett2p@webs.com', 9594, 'Training', 'Västerås', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (99, 'Marinna', 'Keam', 'mkeam2q@webs.com', 1698, 'Sales', 'Falköping', 'SE', 'F');
insert into EMPLOYEE (id, first_name, last_name, email, salary, dept, city, country, gender) values (100, 'Maryrose', 'Lassell', 'mlassell2r@smh.com.au', 9019, 'Accounting', 'Knivsta', 'SE', 'F');
